In [1]:
import cv2
import numpy as np
import math
import os

In [2]:
#image convolve
def co(s_x,pad_image,i):
    img_x = np.asarray([[0 for x in range(0,width)] for y in range(0,height)])
    for x in range (0,height):
        for y in range (0,width):
            su=0
            for k in range (0,3):
                for l in range (0,3):
                    a= pad_image[x-k,y-l]
                    w1 = s_x[k][l];
                    su = su + (w1*a);
            img_x[x,y] = su
    print(img_x)
    d = img_x.shape
    print('edge_'+str(i)+'width, height',d)
    gname = 'edge'+str(i)+'.jpg'
    path = 'A:\\classes\\Intro to Computer vision and Image Processing\\projrct\\project1\\task2'
    cv2.imwrite(os.path.join(path,gname),np.asarray(img_x))
    cv2.imshow('edge_x',np.asarray(img_x,dtype ='uint8'))
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    return img_x


In [12]:
s_x = [[1,0,-1],[2,0,-2],[1,0,-1]]
s_y =[[1,2,1],[0,0,0],[-1,-2,-1]]
#flip
for i in range (0,3):
    temp =s_x[i][0]
    s_x[i][0] =s_x[i][2]
    s_x[i][2] =temp
print('s_x',s_x)
for y in range (0,3):
    temp = s_y[0][y]
    s_y[0][y] =s_y[2][y]
    s_y[2][y] =temp
print('s_y',s_y)

img = cv2.imread('A:\\classes\\Intro to Computer vision and Image Processing\\projrct\\project1\\task1.png',0)
im = np.asarray(img)
print(im)
d = im.shape
height = img.shape[0]
width = img.shape[1]
print('Image Dimension    : ',d)
print('Image Height       : ',height)
print('Image Width        : ',width)
print('Please Wait... Output is processing')
#g_x = img.copy()
#g_y =img.copy()
# newmatrix
pad_image = np.asarray([[0 for x in range (width+2)] for y in range (height+2)])
pad_image[1:-1,1:-1] = img
cv2.imshow('padded',np.asarray(pad_image,dtype = 'uint8'))
cv2.waitKey(0)
cv2.destroyAllWindows()
#g_x = np.asarray([[0 for x in range(0,width)] for y in range(0,height)])
g_x = co(s_x,pad_image,1)
#g_y = np.asarray([[0 for x in range(0,width)] for y in range(0,height)])
g_y = co(s_y,pad_image,2)

edge_magnitude = math.sqrt((g_x*g_x) + ((g_y*g_y)))
edge_magnitude /= np.max(edge_magnitude)
gname = 'edge_magnitude.jpg'
path = 'A:\\classes\\Intro to Computer vision and Image Processing\\projrct\\project1\\task2'
cv2.imwrite(os.path.join(path,gname),np.asarray(edge_magnitude))
cv2.imshow('edge_direction',np.asarray(edge_magnitude,dtype = 'uint8'))
cv2.waitKey(0)
cv2.destroyAllWindows()

s_x [[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]]
s_y [[-1, -2, -1], [0, 0, 0], [1, 2, 1]]
[[203 203 203 ... 247 247 247]
 [203 208 204 ... 247 247 247]
 [204 203 208 ... 247 247 247]
 ...
 [144 147 144 ... 139 147 136]
 [155 152 153 ... 144 152 160]
 [160 160 155 ... 155 160 160]]
Image Dimension    :  (600, 900)
Image Height       :  600
Image Width        :  900
Please Wait... Output is processing
[[ 160 -160 -160 ...    0    5   -5]
 [ 247 -203 -203 ...    0    0    0]
 [ 741 -609 -614 ...    0    0    0]
 ...
 [ 561 -563 -566 ...  -31   -7   -1]
 [ 535 -555 -564 ...  -10  -23  -11]
 [ 562 -579 -585 ...    8   -7  -21]]
edge_1width, height (600, 900)
[[ 160  160  480 ...  630  625  625]
 [-247 -203 -609 ... -988 -988 -988]
 [-247 -203 -614 ... -988 -988 -988]
 ...
 [  23   13   36 ...   93   85   61]
 [   3   -5  -18 ...  -28  -15  -17]
 [ -30  -19  -51 ...  -84  -63  -55]]
edge_2width, height (600, 900)


TypeError: only size-1 arrays can be converted to Python scalars

In [ ]:
import numpy as np 
a = [[0,0,0,0,0],[0,1,2,3,0],[0,4,5,6,0],[0,7,8,9,0],[0,0,0,0,0]]
b = [[-1,-2,-1],[0,0,0],[1,2,1]]
newmatrix = [[0 for x in range (3)]for y in range (3)]
print (newmatrix)
for i in range(5):
    for j in range(5):
        sum =0
        for m in range (3):
            for n in range (3):
                sum = sum +b[m][n]*a[i-m][j-n]
        newmatrix[i-2][j-2] =sum
print(newmatrix)